<?php

namespace Database\Seeders;

use App\Models\KpiTemplate;
use Illuminate\Database\Seeder;

class KpiTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data
        KpiTemplate::truncate();

        // ==================== UNIVERSAL KPIs (8) ====================
        $this->seedUniversalKpis();

        // ==================== FOOD & BEVERAGE KPIs (12) ====================
        $this->seedFoodBeverageKpis();

        // ==================== FASHION & APPAREL KPIs (10) ====================
        $this->seedFashionKpis();

        // ==================== BEAUTY & WELLNESS KPIs (9) ====================
        $this->seedBeautyKpis();

        // ==================== FITNESS & SPORTS KPIs (8) ====================
        $this->seedFitnessKpis();

        // ==================== EDUCATION & TRAINING KPIs (9) ====================
        $this->seedEducationKpis();

        // ==================== E-COMMERCE KPIs (12) ====================
        $this->seedEcommerceKpis();

        $this->command->info('✅ KPI Templates seeded successfully! Total: 68 KPIs');
    }

    /**
     * Seed Universal KPIs (applicable to all businesses)
     */
    protected function seedUniversalKpis(): void
    {
        $kpis = [
            [
                'category' => 'marketing',
                'kpi_code' => 'instagram_follower_growth',
                'kpi_name' => 'Instagram Follower Growth Rate',
                'kpi_name_uz' => 'Instagram Follower O\'sishi',
                'kpi_name_ru' => 'Рост подписчиков Instagram',
                'description' => 'Monthly percentage growth in Instagram followers',
                'description_uz' => 'Instagram followerlar oylik o\'sish foizi',
                'measurement_method' => '((Current Followers - Previous Followers) / Previous Followers) × 100',
                'formula' => '((current_followers - prev_followers) / prev_followers) * 100',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => true,
                'applicable_industries' => ['all'],
                'applicable_subcategories' => ['all'],
                'priority_level' => 'high',
                'default_weight' => 2.0,
                'default_green_threshold' => 90.0,
                'default_yellow_threshold' => 70.0,
                'icon' => '📈',
                'tips' => 'Post consistently, use trending hashtags, engage with followers',
                'tips_uz' => 'Doimiy post qo\'ying, trending hashtaglar ishlating, followerlar bilan muloqot qiling',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'instagram_engagement_rate',
                'kpi_name' => 'Instagram Engagement Rate',
                'kpi_name_uz' => 'Instagram Jalb Qilish Darajasi',
                'kpi_name_ru' => 'Уровень вовлеченности Instagram',
                'description' => 'Percentage of followers who engage with content',
                'description_uz' => 'Kontent bilan muloqot qiladigan followerlar foizi',
                'measurement_method' => '((Likes + Comments + Shares + Saves) / Reach) × 100',
                'formula' => '((likes + comments + shares + saves) / reach) * 100',
                'good_direction' => 'higher',
                'default_frequency' => 'daily',
                'default_unit' => '%',
                'is_universal' => true,
                'applicable_industries' => ['all'],
                'applicable_subcategories' => ['all'],
                'priority_level' => 'critical',
                'default_weight' => 3.0,
                'default_green_threshold' => 90.0,
                'default_yellow_threshold' => 70.0,
                'icon' => '💬',
                'tips' => 'Create interactive content, ask questions, use stories polls',
                'tips_uz' => 'Interaktiv kontent yarating, savollar bering, story poll ishlating',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'dm_response_time',
                'kpi_name' => 'DM Response Time',
                'kpi_name_uz' => 'DM Javob Berish Vaqti',
                'kpi_name_ru' => 'Время ответа в DM',
                'description' => 'Average time to respond to direct messages (in minutes)',
                'description_uz' => 'Direct messagelarga javob berish o\'rtacha vaqti (daqiqada)',
                'measurement_method' => 'Average time from message received to first response',
                'formula' => 'avg(response_time_minutes)',
                'good_direction' => 'lower',
                'default_frequency' => 'daily',
                'default_unit' => 'daqiqa',
                'is_universal' => true,
                'applicable_industries' => ['all'],
                'applicable_subcategories' => ['all'],
                'priority_level' => 'critical',
                'default_weight' => 3.0,
                'default_green_threshold' => 90.0,
                'default_yellow_threshold' => 70.0,
                'icon' => '⏱️',
                'tips' => 'Enable notifications, use quick replies, assign DM manager',
                'tips_uz' => 'Notificationlarni yoqing, tez javoblar qo\'llanying, DM manager tayinlang',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'lead_volume',
                'kpi_name' => 'Lead Volume',
                'kpi_name_uz' => 'Lid Hajmi',
                'kpi_name_ru' => 'Объем лидов',
                'description' => 'Total number of leads generated (DM + Comment + Call + Form)',
                'description_uz' => 'Yaratilgan lidlar soni (DM + Izoh + Qo\'ng\'iroq + Forma)',
                'measurement_method' => 'Count all new lead inquiries from all channels',
                'formula' => 'count(leads)',
                'good_direction' => 'higher',
                'default_frequency' => 'daily',
                'default_unit' => 'dona',
                'is_universal' => true,
                'applicable_industries' => ['all'],
                'applicable_subcategories' => ['all'],
                'priority_level' => 'critical',
                'default_weight' => 3.0,
                'default_green_threshold' => 90.0,
                'default_yellow_threshold' => 70.0,
                'icon' => '👥',
                'tips' => 'Clear CTA in posts, lead magnets, landing pages, ads',
                'tips_uz' => 'Postlarda aniq CTA, lead magnet, landing page, reklama',
                'is_active' => true,
            ],
            [
                'category' => 'sales',
                'kpi_code' => 'conversion_rate',
                'kpi_name' => 'Conversion Rate (Lead to Customer)',
                'kpi_name_uz' => 'Konversiya Darajasi (Lid → Mijoz)',
                'kpi_name_ru' => 'Коэффициент конверсии (Лид → Клиент)',
                'description' => 'Percentage of leads that become paying customers',
                'description_uz' => 'To\'lovchi mijozga aylanadigan lidlar foizi',
                'measurement_method' => '(New Customers / Total Leads) × 100',
                'formula' => '(customers / leads) * 100',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => '%',
                'is_universal' => true,
                'applicable_industries' => ['all'],
                'applicable_subcategories' => ['all'],
                'priority_level' => 'critical',
                'default_weight' => 3.0,
                'default_green_threshold' => 90.0,
                'default_yellow_threshold' => 70.0,
                'icon' => '🎯',
                'tips' => 'Qualify leads properly, follow up consistently, remove friction',
                'tips_uz' => 'Lidlarni to\'g\'ri saralang, doimiy follow-up qiling, to\'siqlarni olib tashlang',
                'is_active' => true,
            ],
            [
                'category' => 'financial',
                'kpi_code' => 'customer_acquisition_cost',
                'kpi_name' => 'Customer Acquisition Cost (CAC)',
                'kpi_name_uz' => 'Mijoz Olish Xarajati',
                'kpi_name_ru' => 'Стоимость привлечения клиента',
                'description' => 'Total marketing cost divided by new customers acquired',
                'description_uz' => 'Umumiy marketing xarajat / yangi mijozlar soni',
                'measurement_method' => 'Total Marketing Spend / New Customers',
                'formula' => 'marketing_spend / new_customers',
                'good_direction' => 'lower',
                'default_frequency' => 'monthly',
                'default_unit' => 'UZS',
                'is_universal' => true,
                'applicable_industries' => ['all'],
                'applicable_subcategories' => ['all'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'default_green_threshold' => 90.0,
                'default_yellow_threshold' => 70.0,
                'icon' => '💰',
                'tips' => 'Optimize ad targeting, improve conversion rate, use organic channels',
                'tips_uz' => 'Reklama targetingni yaxshilang, konversiyani oshiring, organic kanallardan foydalaning',
                'is_active' => true,
            ],
            [
                'category' => 'financial',
                'kpi_code' => 'monthly_revenue',
                'kpi_name' => 'Monthly Revenue',
                'kpi_name_uz' => 'Oylik Daromad',
                'kpi_name_ru' => 'Месячная выручка',
                'description' => 'Total revenue generated in a month',
                'description_uz' => 'Oyda yaratilgan umumiy daromad',
                'measurement_method' => 'Sum of all sales revenue in the month',
                'formula' => 'sum(sales)',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => 'UZS',
                'is_universal' => true,
                'applicable_industries' => ['all'],
                'applicable_subcategories' => ['all'],
                'priority_level' => 'critical',
                'default_weight' => 3.0,
                'default_green_threshold' => 90.0,
                'default_yellow_threshold' => 70.0,
                'icon' => '💵',
                'tips' => 'Upsell, cross-sell, increase prices, acquire more customers',
                'tips_uz' => 'Upsell, cross-sell, narxlarni oshiring, ko\'proq mijoz jalb qiling',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'google_review_rating',
                'kpi_name' => 'Google Review Count & Rating',
                'kpi_name_uz' => 'Google Sharh Soni va Reytingi',
                'kpi_name_ru' => 'Количество и рейтинг отзывов Google',
                'description' => 'Number of Google reviews and average rating',
                'description_uz' => 'Google sharhlari soni va o\'rtacha reyting',
                'measurement_method' => 'Track review count growth and maintain rating above 4.5',
                'formula' => 'avg(rating)',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => 'dona',
                'is_universal' => true,
                'applicable_industries' => ['all'],
                'applicable_subcategories' => ['all'],
                'priority_level' => 'high',
                'default_weight' => 2.0,
                'default_green_threshold' => 90.0,
                'default_yellow_threshold' => 70.0,
                'icon' => '⭐',
                'tips' => 'Ask satisfied customers for reviews, respond to all reviews, improve service',
                'tips_uz' => 'Mamnun mijozlardan sharh so\'rang, barcha sharhlarga javob bering, xizmatni yaxshilang',
                'is_active' => true,
            ],
        ];

        foreach ($kpis as $kpi) {
            KpiTemplate::create($kpi);
        }

        $this->command->info('✓ Universal KPIs seeded (8)');
    }

    /**
     * Seed Food & Beverage specific KPIs
     */
    protected function seedFoodBeverageKpis(): void
    {
        $kpis = [
            [
                'category' => 'marketing',
                'kpi_code' => 'booking_inquiry_volume',
                'kpi_name' => 'Booking Inquiry Volume',
                'kpi_name_uz' => 'Rezervatsiya So\'rovlari Hajmi',
                'kpi_name_ru' => 'Объем запросов на бронирование',
                'description' => 'Number of reservation requests received',
                'description_uz' => 'Qabul qilingan rezervatsiya so\'rovlari soni',
                'measurement_method' => 'Count all booking inquiries (DM, call, online form)',
                'formula' => 'count(booking_requests)',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => 'dona',
                'is_universal' => false,
                'applicable_industries' => ['food_beverage'],
                'applicable_subcategories' => ['restaurant_fine_dining', 'coffee_shop'],
                'priority_level' => 'critical',
                'default_weight' => 3.0,
                'icon' => '📅',
                'is_active' => true,
            ],
            [
                'category' => 'sales',
                'kpi_code' => 'booking_conversion_rate',
                'kpi_name' => 'Booking Conversion Rate',
                'kpi_name_uz' => 'Rezervatsiya Konversiya Darajasi',
                'kpi_name_ru' => 'Коэффициент конверсии бронирований',
                'description' => 'Percentage of booking inquiries that become confirmed reservations',
                'description_uz' => 'Tasdiqlangan rezervatsiyaga aylanadigan so\'rovlar foizi',
                'measurement_method' => '(Confirmed Bookings / Booking Inquiries) × 100',
                'formula' => '(confirmed_bookings / inquiries) * 100',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['food_beverage'],
                'applicable_subcategories' => ['restaurant_fine_dining', 'coffee_shop'],
                'priority_level' => 'critical',
                'default_weight' => 3.0,
                'icon' => '✅',
                'is_active' => true,
            ],
            [
                'category' => 'operational',
                'kpi_code' => 'table_turnover_rate',
                'kpi_name' => 'Table Turnover Rate',
                'kpi_name_uz' => 'Stol Aylanishi',
                'kpi_name_ru' => 'Оборачиваемость столов',
                'description' => 'Average number of times a table is occupied per service period',
                'description_uz' => 'Xizmat davrida stolning band bo\'lish o\'rtacha soni',
                'measurement_method' => 'Total Covers / Number of Tables / Service Periods',
                'formula' => 'total_covers / tables / periods',
                'good_direction' => 'higher',
                'default_frequency' => 'daily',
                'default_unit' => 'marta',
                'is_universal' => false,
                'applicable_industries' => ['food_beverage'],
                'applicable_subcategories' => ['restaurant_fine_dining', 'fast_food'],
                'priority_level' => 'high',
                'default_weight' => 2.0,
                'icon' => '🔄',
                'is_active' => true,
            ],
            [
                'category' => 'sales',
                'kpi_code' => 'average_check_size',
                'kpi_name' => 'Average Check Size',
                'kpi_name_uz' => 'O\'rtacha Chek Hajmi',
                'kpi_name_ru' => 'Средний чек',
                'description' => 'Average revenue per customer transaction',
                'description_uz' => 'Har bir mijoz tranzaksiyasi uchun o\'rtacha daromad',
                'measurement_method' => 'Total Revenue / Number of Transactions',
                'formula' => 'revenue / transactions',
                'good_direction' => 'higher',
                'default_frequency' => 'daily',
                'default_unit' => 'UZS',
                'is_universal' => false,
                'applicable_industries' => ['food_beverage'],
                'applicable_subcategories' => ['restaurant_fine_dining', 'fast_food', 'coffee_shop'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'icon' => '🧾',
                'tips' => 'Upsell drinks, desserts, combos',
                'tips_uz' => 'Ichimlik, desert, kombo taklif qiling',
                'is_active' => true,
            ],
            [
                'category' => 'operational',
                'kpi_code' => 'no_show_rate',
                'kpi_name' => 'No-Show Rate',
                'kpi_name_uz' => 'Kelmaslik Darajasi',
                'kpi_name_ru' => 'Процент неявок',
                'description' => 'Percentage of confirmed reservations where customers do not show up',
                'description_uz' => 'Mijozlar kelmaydigan tasdiqlangan rezervatsiyalar foizi',
                'measurement_method' => '(No-Shows / Confirmed Bookings) × 100',
                'formula' => '(no_shows / confirmed_bookings) * 100',
                'good_direction' => 'lower',
                'default_frequency' => 'weekly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['food_beverage'],
                'applicable_subcategories' => ['restaurant_fine_dining'],
                'priority_level' => 'medium',
                'default_weight' => 1.5,
                'icon' => '🚫',
                'tips' => 'Send reminders, require deposits, overbook slightly',
                'tips_uz' => 'Eslatma yuboring, depozit oling, biroz ko\'proq booking qiling',
                'is_active' => true,
            ],
            [
                'category' => 'retention',
                'kpi_code' => 'repeat_visit_rate',
                'kpi_name' => 'Repeat Visit Rate',
                'kpi_name_uz' => 'Qayta Tashrif Darajasi',
                'kpi_name_ru' => 'Процент повторных визитов',
                'description' => 'Percentage of customers who return within 3 months',
                'description_uz' => '3 oy ichida qaytib keladigan mijozlar foizi',
                'measurement_method' => '(Repeat Customers / Total Customers) × 100',
                'formula' => '(repeat_customers / total_customers) * 100',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['food_beverage'],
                'applicable_subcategories' => ['restaurant_fine_dining', 'coffee_shop', 'fast_food'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'min_business_age' => 'growing',
                'icon' => '🔁',
                'is_active' => true,
            ],
            [
                'category' => 'operational',
                'kpi_code' => 'menu_item_popularity',
                'kpi_name' => 'Menu Item Popularity',
                'kpi_name_uz' => 'Menyu Mahsulot Ommabopligi',
                'kpi_name_ru' => 'Популярность блюд',
                'description' => 'Percentage of sales from top 5 dishes',
                'description_uz' => 'Top 5 taomdan sotuv foizi',
                'measurement_method' => '(Top 5 Items Sales / Total Sales) × 100',
                'formula' => '(top5_sales / total_sales) * 100',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['food_beverage'],
                'applicable_subcategories' => ['restaurant_fine_dining', 'fast_food'],
                'priority_level' => 'medium',
                'default_weight' => 1.0,
                'icon' => '🍽️',
                'is_active' => true,
            ],
            [
                'category' => 'operational',
                'kpi_code' => 'delivery_order_percentage',
                'kpi_name' => 'Delivery Order Percentage',
                'kpi_name_uz' => 'Yetkazib Berish Buyurtma Foizi',
                'kpi_name_ru' => 'Процент заказов на доставку',
                'description' => 'Percentage of total orders that are delivery',
                'description_uz' => 'Yetkazib berish bo\'yicha buyurtmalar foizi',
                'measurement_method' => '(Delivery Orders / Total Orders) × 100',
                'formula' => '(delivery_orders / total_orders) * 100',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['food_beverage'],
                'applicable_subcategories' => ['fast_food', 'restaurant_fine_dining'],
                'priority_level' => 'medium',
                'default_weight' => 1.5,
                'icon' => '🛵',
                'is_active' => true,
            ],
            [
                'category' => 'operational',
                'kpi_code' => 'peak_hour_revenue_percentage',
                'kpi_name' => 'Peak Hour Revenue Percentage',
                'kpi_name_uz' => 'Eng Ko\'p Soatlar Daromad Foizi',
                'kpi_name_ru' => 'Процент выручки в пиковые часы',
                'description' => 'Percentage of daily revenue during peak hours',
                'description_uz' => 'Eng ko\'p soatlardagi kunlik daromad foizi',
                'measurement_method' => '(Peak Hours Revenue / Total Daily Revenue) × 100',
                'formula' => '(peak_revenue / daily_revenue) * 100',
                'good_direction' => 'higher',
                'default_frequency' => 'daily',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['food_beverage'],
                'applicable_subcategories' => ['coffee_shop', 'fast_food'],
                'priority_level' => 'medium',
                'default_weight' => 1.0,
                'icon' => '⏰',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'story_menu_showcase_views',
                'kpi_name' => 'Story Menu Showcase Views',
                'kpi_name_uz' => 'Story Menyu Ko\'rsatish Ko\'rishlari',
                'kpi_name_ru' => 'Просмотры меню в Stories',
                'description' => 'Number of views on Instagram Stories featuring menu items',
                'description_uz' => 'Menyu mahsulotlarini ko\'rsatuvchi Instagram Story ko\'rishlari',
                'measurement_method' => 'Count story views where menu items are featured',
                'formula' => 'sum(menu_story_views)',
                'good_direction' => 'higher',
                'default_frequency' => 'daily',
                'default_unit' => 'dona',
                'is_universal' => false,
                'applicable_industries' => ['food_beverage'],
                'applicable_subcategories' => ['restaurant_fine_dining', 'coffee_shop', 'fast_food'],
                'priority_level' => 'high',
                'default_weight' => 2.0,
                'icon' => '📸',
                'is_active' => true,
            ],
            [
                'category' => 'retention',
                'kpi_code' => 'loyalty_program_signups',
                'kpi_name' => 'Loyalty Program Sign-ups',
                'kpi_name_uz' => 'Sodiqlik Dasturiga Ro\'yxatdan O\'tish',
                'kpi_name_ru' => 'Регистрации в программе лояльности',
                'description' => 'Number of new loyalty program members',
                'description_uz' => 'Yangi sodiqlik dasturi a\'zolari soni',
                'measurement_method' => 'Count new loyalty program registrations',
                'formula' => 'count(new_members)',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => 'dona',
                'is_universal' => false,
                'applicable_industries' => ['food_beverage'],
                'applicable_subcategories' => ['coffee_shop', 'fast_food'],
                'priority_level' => 'medium',
                'default_weight' => 1.5,
                'min_business_age' => 'growing',
                'icon' => '🎁',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'user_generated_food_content',
                'kpi_name' => 'User-Generated Content (Food Photos)',
                'kpi_name_uz' => 'Foydalanuvchi Yaratgan Kontent (Taom Rasmlari)',
                'kpi_name_ru' => 'Пользовательский контент (Фото еды)',
                'description' => 'Number of customer photos tagged or mentioning the restaurant',
                'description_uz' => 'Restoranni tag qilgan yoki eslatgan mijoz rasmlari soni',
                'measurement_method' => 'Count Instagram posts tagging the business or using branded hashtags',
                'formula' => 'count(tagged_posts)',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => 'dona',
                'is_universal' => false,
                'applicable_industries' => ['food_beverage'],
                'applicable_subcategories' => ['restaurant_fine_dining', 'coffee_shop'],
                'priority_level' => 'medium',
                'default_weight' => 1.5,
                'icon' => '📷',
                'is_active' => true,
            ],
        ];

        foreach ($kpis as $kpi) {
            KpiTemplate::create($kpi);
        }

        $this->command->info('✓ Food & Beverage KPIs seeded (12)');
    }

    /**
     * Seed Fashion & Apparel specific KPIs
     */
    protected function seedFashionKpis(): void
    {
        $kpis = [
            [
                'category' => 'marketing',
                'kpi_code' => 'reel_virality_rate',
                'kpi_name' => 'Reel Virality Rate',
                'kpi_name_uz' => 'Reel Virallik Darajasi',
                'kpi_name_ru' => 'Процент виральности Reels',
                'description' => 'Percentage of Reels that reach over 10,000 views',
                'description_uz' => '10,000 dan ortiq ko\'rilgan Reellar foizi',
                'measurement_method' => '(Reels with >10k views / Total Reels) × 100',
                'formula' => '(viral_reels / total_reels) * 100',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['fashion_retail'],
                'applicable_subcategories' => ['fashion_boutique', 'casual_wear'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'icon' => '🎬',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'influencer_collaboration_count',
                'kpi_name' => 'Influencer Collaboration Count',
                'kpi_name_uz' => 'Influencer Hamkorlik Soni',
                'kpi_name_ru' => 'Количество коллабораций с инфлюенсерами',
                'description' => 'Number of influencer partnerships per month',
                'description_uz' => 'Oylik influencer hamkorliklari soni',
                'measurement_method' => 'Count active influencer collaborations',
                'formula' => 'count(collaborations)',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => 'dona',
                'is_universal' => false,
                'applicable_industries' => ['fashion_retail'],
                'applicable_subcategories' => ['fashion_boutique'],
                'priority_level' => 'high',
                'default_weight' => 2.0,
                'icon' => '🤝',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'lookbook_post_engagement',
                'kpi_name' => 'Lookbook/Collection Post Engagement',
                'kpi_name_uz' => 'Lookbook/Kolleksiya Post Jalb Qilish',
                'kpi_name_ru' => 'Вовлеченность постов коллекций',
                'description' => 'Engagement rate on lookbook and new collection posts',
                'description_uz' => 'Lookbook va yangi kolleksiya postlarida jalb qilish darajasi',
                'measurement_method' => '((Likes + Comments + Shares) / Reach) × 100 for collection posts',
                'formula' => '((likes + comments + shares) / reach) * 100',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['fashion_retail'],
                'applicable_subcategories' => ['fashion_boutique', 'casual_wear'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'icon' => '👗',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'brand_mention_tag_count',
                'kpi_name' => 'Brand Mention & Tag Count',
                'kpi_name_uz' => 'Brend Eslatma va Tag Soni',
                'kpi_name_ru' => 'Количество упоминаний и тегов бренда',
                'description' => 'Number of times customers tag or mention the brand',
                'description_uz' => 'Mijozlar brendni tag qilish yoki eslatish soni',
                'measurement_method' => 'Count @mentions and hashtag uses',
                'formula' => 'count(mentions + tags)',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => 'dona',
                'is_universal' => false,
                'applicable_industries' => ['fashion_retail'],
                'applicable_subcategories' => ['fashion_boutique', 'casual_wear'],
                'priority_level' => 'medium',
                'default_weight' => 1.5,
                'icon' => '🏷️',
                'is_active' => true,
            ],
            [
                'category' => 'operational',
                'kpi_code' => 'collection_sell_through_rate',
                'kpi_name' => 'Collection Sell-Through Rate',
                'kpi_name_uz' => 'Kolleksiya Sotilish Darajasi',
                'kpi_name_ru' => 'Процент продаж коллекции',
                'description' => 'Percentage of collection items sold within season',
                'description_uz' => 'Mavsumda sotilgan kolleksiya mahsulotlari foizi',
                'measurement_method' => '(Units Sold / Units Ordered) × 100',
                'formula' => '(sold / ordered) * 100',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['fashion_retail'],
                'applicable_subcategories' => ['fashion_boutique'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'icon' => '📊',
                'is_active' => true,
            ],
            [
                'category' => 'sales',
                'kpi_code' => 'preorder_conversion_rate',
                'kpi_name' => 'Pre-Order Conversion Rate',
                'kpi_name_uz' => 'Oldindan Buyurtma Konversiya Darajasi',
                'kpi_name_ru' => 'Конверсия предзаказов',
                'description' => 'Percentage of announced products that get pre-ordered',
                'description_uz' => 'E\'lon qilingan mahsulotlardan oldindan buyurtma beriladiganlar foizi',
                'measurement_method' => '(Pre-Orders / Product Announcements) × 100',
                'formula' => '(preorders / announcements) * 100',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['fashion_retail'],
                'applicable_subcategories' => ['fashion_boutique'],
                'priority_level' => 'medium',
                'default_weight' => 1.5,
                'icon' => '🎁',
                'is_active' => true,
            ],
            [
                'category' => 'retention',
                'kpi_code' => 'customer_lifetime_value_fashion',
                'kpi_name' => 'Customer Lifetime Value',
                'kpi_name_uz' => 'Mijoz Hayotiy Qiymati',
                'kpi_name_ru' => 'Пожизненная ценность клиента',
                'description' => 'Total revenue expected from a customer over their lifetime',
                'description_uz' => 'Mijozdan kutilayotgan umumiy daromad',
                'measurement_method' => 'AOV × Purchase Frequency × Customer Lifespan',
                'formula' => 'aov * frequency * lifespan',
                'good_direction' => 'higher',
                'default_frequency' => 'quarterly',
                'default_unit' => 'UZS',
                'is_universal' => false,
                'applicable_industries' => ['fashion_retail'],
                'applicable_subcategories' => ['fashion_boutique', 'casual_wear'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'min_business_age' => 'established',
                'icon' => '💎',
                'is_active' => true,
            ],
            [
                'category' => 'sales',
                'kpi_code' => 'average_order_value_fashion',
                'kpi_name' => 'Average Order Value',
                'kpi_name_uz' => 'O\'rtacha Buyurtma Qiymati',
                'kpi_name_ru' => 'Средняя стоимость заказа',
                'description' => 'Average amount spent per order',
                'description_uz' => 'Har bir buyurtma uchun o\'rtacha xarajat',
                'measurement_method' => 'Total Revenue / Number of Orders',
                'formula' => 'revenue / orders',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => 'UZS',
                'is_universal' => false,
                'applicable_industries' => ['fashion_retail'],
                'applicable_subcategories' => ['fashion_boutique', 'casual_wear'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'icon' => '🛍️',
                'is_active' => true,
            ],
            [
                'category' => 'retention',
                'kpi_code' => 'repeat_purchase_rate_fashion',
                'kpi_name' => 'Repeat Purchase Rate',
                'kpi_name_uz' => 'Qayta Xarid Qilish Darajasi',
                'kpi_name_ru' => 'Процент повторных покупок',
                'description' => 'Percentage of customers who make multiple purchases',
                'description_uz' => 'Bir necha marta xarid qiladigan mijozlar foizi',
                'measurement_method' => '(Repeat Customers / Total Customers) × 100',
                'formula' => '(repeat / total) * 100',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['fashion_retail'],
                'applicable_subcategories' => ['fashion_boutique', 'casual_wear'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'min_business_age' => 'growing',
                'icon' => '🔁',
                'is_active' => true,
            ],
            [
                'category' => 'operational',
                'kpi_code' => 'product_return_rate',
                'kpi_name' => 'Product Return Rate',
                'kpi_name_uz' => 'Mahsulot Qaytarish Darajasi',
                'kpi_name_ru' => 'Процент возвратов',
                'description' => 'Percentage of sold items that are returned',
                'description_uz' => 'Qaytarilgan sotilgan mahsulotlar foizi',
                'measurement_method' => '(Returns / Total Sales) × 100',
                'formula' => '(returns / sales) * 100',
                'good_direction' => 'lower',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['fashion_retail'],
                'applicable_subcategories' => ['fashion_boutique', 'casual_wear', 'online_fashion'],
                'priority_level' => 'medium',
                'default_weight' => 1.5,
                'icon' => '↩️',
                'is_active' => true,
            ],
        ];

        foreach ($kpis as $kpi) {
            KpiTemplate::create($kpi);
        }

        $this->command->info('✓ Fashion & Apparel KPIs seeded (10)');
    }

    /**
     * Seed Beauty & Wellness specific KPIs
     */
    protected function seedBeautyKpis(): void
    {
        $kpis = [
            [
                'category' => 'marketing',
                'kpi_code' => 'before_after_engagement',
                'kpi_name' => 'Before/After Post Engagement',
                'kpi_name_uz' => 'Oldin/Keyin Post Jalb Qilish',
                'description' => 'Engagement rate on transformation posts',
                'measurement_method' => 'Engagement rate on before/after photos',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['beauty_wellness'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'icon' => '✨',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'appointment_request_volume',
                'kpi_name' => 'Appointment Request Volume',
                'kpi_name_uz' => 'Uchrashuv So\'rovlari Hajmi',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => 'dona',
                'is_universal' => false,
                'applicable_industries' => ['beauty_wellness'],
                'priority_level' => 'critical',
                'default_weight' => 3.0,
                'icon' => '📅',
                'is_active' => true,
            ],
            [
                'category' => 'sales',
                'kpi_code' => 'appointment_booking_rate',
                'kpi_name' => 'Appointment Booking Rate',
                'kpi_name_uz' => 'Uchrashuv Booking Darajasi',
                'measurement_method' => '(Booked / Requests) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['beauty_wellness'],
                'priority_level' => 'critical',
                'default_weight' => 3.0,
                'icon' => '✅',
                'is_active' => true,
            ],
            [
                'category' => 'operational',
                'kpi_code' => 'appointment_fulfillment_rate',
                'kpi_name' => 'Appointment Fulfillment Rate (No-Show)',
                'kpi_name_uz' => 'Uchrashuv Bajarilish Darajasi',
                'measurement_method' => '(Attended / Booked) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['beauty_wellness'],
                'priority_level' => 'high',
                'default_weight' => 2.0,
                'icon' => '👤',
                'is_active' => true,
            ],
            [
                'category' => 'sales',
                'kpi_code' => 'service_addon_rate',
                'kpi_name' => 'Service Add-On Rate',
                'kpi_name_uz' => 'Xizmat Qo\'shimcha Darajasi',
                'measurement_method' => '(Customers buying add-ons / Total) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['beauty_wellness'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'icon' => '💅',
                'is_active' => true,
            ],
            [
                'category' => 'retention',
                'kpi_code' => 'repeat_appointment_rate',
                'kpi_name' => 'Repeat Appointment Rate',
                'kpi_name_uz' => 'Qayta Uchrashuv Darajasi',
                'measurement_method' => '(Returning customers / Total) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['beauty_wellness'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'min_business_age' => 'growing',
                'icon' => '🔁',
                'is_active' => true,
            ],
            [
                'category' => 'operational',
                'kpi_code' => 'stylist_utilization_rate',
                'kpi_name' => 'Stylist Utilization Rate',
                'kpi_name_uz' => 'Stilist Foydalanish Darajasi',
                'measurement_method' => '(Booked Hours / Available Hours) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['beauty_wellness'],
                'priority_level' => 'medium',
                'default_weight' => 1.5,
                'icon' => '💼',
                'is_active' => true,
            ],
            [
                'category' => 'sales',
                'kpi_code' => 'average_service_value',
                'kpi_name' => 'Average Service Value',
                'kpi_name_uz' => 'O\'rtacha Xizmat Qiymati',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => 'UZS',
                'is_universal' => false,
                'applicable_industries' => ['beauty_wellness'],
                'priority_level' => 'high',
                'default_weight' => 2.0,
                'icon' => '💰',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'tutorial_content_engagement',
                'kpi_name' => 'Tutorial Content Engagement',
                'kpi_name_uz' => 'Tutorial Kontent Jalb Qilish',
                'measurement_method' => 'Engagement on tutorial/how-to posts',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['beauty_wellness'],
                'applicable_subcategories' => ['cosmetics_shop'],
                'priority_level' => 'medium',
                'default_weight' => 1.5,
                'icon' => '📹',
                'is_active' => true,
            ],
        ];

        foreach ($kpis as $kpi) {
            KpiTemplate::create($kpi);
        }

        $this->command->info('✓ Beauty & Wellness KPIs seeded (9)');
    }

    /**
     * Seed Fitness & Sports specific KPIs
     */
    protected function seedFitnessKpis(): void
    {
        $kpis = [
            [
                'category' => 'marketing',
                'kpi_code' => 'transformation_post_reach',
                'kpi_name' => 'Transformation Post Reach',
                'kpi_name_uz' => 'Transformatsiya Post Qamrovi',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => 'dona',
                'is_universal' => false,
                'applicable_industries' => ['fitness_sports'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'icon' => '💪',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'free_trial_request_volume',
                'kpi_name' => 'Free Trial Request Volume',
                'kpi_name_uz' => 'Bepul Sinov So\'rovlari',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => 'dona',
                'is_universal' => false,
                'applicable_industries' => ['fitness_sports'],
                'priority_level' => 'critical',
                'default_weight' => 3.0,
                'icon' => '🎟️',
                'is_active' => true,
            ],
            [
                'category' => 'sales',
                'kpi_code' => 'trial_to_membership_conversion',
                'kpi_name' => 'Trial-to-Membership Conversion',
                'kpi_name_uz' => 'Sinov→A\'zolik Konversiyasi',
                'measurement_method' => '(Members / Trials) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['fitness_sports'],
                'priority_level' => 'critical',
                'default_weight' => 3.0,
                'icon' => '🎯',
                'is_active' => true,
            ],
            [
                'category' => 'retention',
                'kpi_code' => 'membership_retention_rate',
                'kpi_name' => 'Membership Retention Rate',
                'kpi_name_uz' => 'A\'zolikni Saqlash Darajasi',
                'measurement_method' => '(Retained / Total Members) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['fitness_sports'],
                'priority_level' => 'critical',
                'default_weight' => 3.0,
                'min_business_age' => 'growing',
                'icon' => '🔒',
                'is_active' => true,
            ],
            [
                'category' => 'retention',
                'kpi_code' => 'three_month_retention_rate',
                'kpi_name' => '3-Month Retention Rate',
                'kpi_name_uz' => '3-Oylik Saqlash Darajasi',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['fitness_sports'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'min_business_age' => 'growing',
                'icon' => '📊',
                'is_active' => true,
            ],
            [
                'category' => 'sales',
                'kpi_code' => 'personal_training_upsell_rate',
                'kpi_name' => 'Upsell Rate (Personal Training)',
                'kpi_name_uz' => 'Personal Training Upsell',
                'measurement_method' => '(PT Buyers / Members) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['fitness_sports'],
                'priority_level' => 'high',
                'default_weight' => 2.0,
                'icon' => '🏋️',
                'is_active' => true,
            ],
            [
                'category' => 'operational',
                'kpi_code' => 'member_checkin_frequency',
                'kpi_name' => 'Member Check-In Frequency',
                'kpi_name_uz' => 'A\'zo Kelish Chastotasi',
                'measurement_method' => 'Average visits per member per week',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => 'marta',
                'is_universal' => false,
                'applicable_industries' => ['fitness_sports'],
                'priority_level' => 'medium',
                'default_weight' => 1.5,
                'icon' => '📍',
                'is_active' => true,
            ],
            [
                'category' => 'operational',
                'kpi_code' => 'peak_hour_capacity_utilization',
                'kpi_name' => 'Peak Hour Capacity Utilization',
                'kpi_name_uz' => 'Eng Ko\'p Soat Sig\'im Foydalanish',
                'measurement_method' => '(Peak Members / Capacity) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['fitness_sports'],
                'priority_level' => 'medium',
                'default_weight' => 1.0,
                'icon' => '⏰',
                'is_active' => true,
            ],
        ];

        foreach ($kpis as $kpi) {
            KpiTemplate::create($kpi);
        }

        $this->command->info('✓ Fitness & Sports KPIs seeded (8)');
    }

    /**
     * Seed Education & Training specific KPIs
     */
    protected function seedEducationKpis(): void
    {
        $kpis = [
            [
                'category' => 'marketing',
                'kpi_code' => 'webinar_registration_rate',
                'kpi_name' => 'Webinar Registration Rate',
                'kpi_name_uz' => 'Vebinar Ro\'yxatdan O\'tish',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => 'dona',
                'is_universal' => false,
                'applicable_industries' => ['education_training'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'icon' => '🎓',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'lead_magnet_download_count',
                'kpi_name' => 'Lead Magnet Download Count',
                'kpi_name_uz' => 'Lead Magnet Yuklab Olish',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => 'dona',
                'is_universal' => false,
                'applicable_industries' => ['education_training'],
                'priority_level' => 'high',
                'default_weight' => 2.0,
                'icon' => '📥',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'email_open_rate_edu',
                'kpi_name' => 'Email Open Rate',
                'kpi_name_uz' => 'Email Ochish Darajasi',
                'measurement_method' => '(Opens / Sent) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['education_training'],
                'priority_level' => 'medium',
                'default_weight' => 1.5,
                'icon' => '📧',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'email_click_rate_edu',
                'kpi_name' => 'Email Click Rate',
                'kpi_name_uz' => 'Email Bosish Darajasi',
                'measurement_method' => '(Clicks / Opens) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['education_training'],
                'priority_level' => 'medium',
                'default_weight' => 1.5,
                'icon' => '🖱️',
                'is_active' => true,
            ],
            [
                'category' => 'sales',
                'kpi_code' => 'course_enrollment_conversion',
                'kpi_name' => 'Course Enrollment Conversion',
                'kpi_name_uz' => 'Kursga Yozilish Konversiyasi',
                'measurement_method' => '(Enrollments / Leads) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['education_training'],
                'priority_level' => 'critical',
                'default_weight' => 3.0,
                'icon' => '🎯',
                'is_active' => true,
            ],
            [
                'category' => 'sales',
                'kpi_code' => 'course_upsell_rate',
                'kpi_name' => 'Upsell Rate (Basic → Premium)',
                'kpi_name_uz' => 'Upsell Darajasi',
                'measurement_method' => '(Premium / Basic) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['education_training'],
                'priority_level' => 'high',
                'default_weight' => 2.0,
                'icon' => '⬆️',
                'is_active' => true,
            ],
            [
                'category' => 'operational',
                'kpi_code' => 'course_completion_rate',
                'kpi_name' => 'Course Completion Rate',
                'kpi_name_uz' => 'Kurs Tugatish Darajasi',
                'measurement_method' => '(Completed / Enrolled) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['education_training'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'icon' => '🏁',
                'is_active' => true,
            ],
            [
                'category' => 'retention',
                'kpi_code' => 'student_lifetime_value',
                'kpi_name' => 'Student Lifetime Value',
                'kpi_name_uz' => 'Talaba Hayotiy Qiymati',
                'good_direction' => 'higher',
                'default_frequency' => 'quarterly',
                'default_unit' => 'UZS',
                'is_universal' => false,
                'applicable_industries' => ['education_training'],
                'priority_level' => 'high',
                'default_weight' => 2.0,
                'min_business_age' => 'established',
                'icon' => '💎',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'referral_revenue_percentage',
                'kpi_name' => 'Referral Revenue %',
                'kpi_name_uz' => 'Tavsiya Daromad Foizi',
                'measurement_method' => '(Referral Revenue / Total) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['education_training'],
                'priority_level' => 'medium',
                'default_weight' => 1.5,
                'min_business_age' => 'growing',
                'icon' => '🤝',
                'is_active' => true,
            ],
        ];

        foreach ($kpis as $kpi) {
            KpiTemplate::create($kpi);
        }

        $this->command->info('✓ Education & Training KPIs seeded (9)');
    }

    /**
     * Seed E-Commerce specific KPIs
     */
    protected function seedEcommerceKpis(): void
    {
        $kpis = [
            [
                'category' => 'marketing',
                'kpi_code' => 'website_traffic_volume',
                'kpi_name' => 'Website Traffic Volume',
                'kpi_name_uz' => 'Website Trafik Hajmi',
                'good_direction' => 'higher',
                'default_frequency' => 'daily',
                'default_unit' => 'dona',
                'is_universal' => false,
                'applicable_industries' => ['ecommerce'],
                'priority_level' => 'critical',
                'default_weight' => 3.0,
                'icon' => '🌐',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'traffic_source_diversity',
                'kpi_name' => 'Traffic Source Diversity',
                'kpi_name_uz' => 'Trafik Manba Xilma-xilligi',
                'description' => 'No single source should exceed 40%',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['ecommerce'],
                'priority_level' => 'medium',
                'default_weight' => 1.0,
                'icon' => '📊',
                'is_active' => true,
            ],
            [
                'category' => 'sales',
                'kpi_code' => 'website_conversion_rate',
                'kpi_name' => 'Website Conversion Rate',
                'kpi_name_uz' => 'Website Konversiya Darajasi',
                'measurement_method' => '(Buyers / Visitors) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'daily',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['ecommerce'],
                'priority_level' => 'critical',
                'default_weight' => 3.0,
                'icon' => '🎯',
                'is_active' => true,
            ],
            [
                'category' => 'operational',
                'kpi_code' => 'cart_abandonment_rate',
                'kpi_name' => 'Cart Abandonment Rate',
                'kpi_name_uz' => 'Savatni Tashlab Ketish',
                'measurement_method' => '(Abandoned / Started) × 100',
                'good_direction' => 'lower',
                'default_frequency' => 'daily',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['ecommerce'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'icon' => '🛒',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'cart_recovery_rate',
                'kpi_name' => 'Cart Abandonment Recovery Rate',
                'kpi_name_uz' => 'Savat Qaytarish Darajasi',
                'measurement_method' => '(Recovered / Abandoned) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'weekly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['ecommerce'],
                'priority_level' => 'high',
                'default_weight' => 2.0,
                'icon' => '💌',
                'is_active' => true,
            ],
            [
                'category' => 'sales',
                'kpi_code' => 'average_order_value_ecom',
                'kpi_name' => 'Average Order Value',
                'kpi_name_uz' => 'O\'rtacha Buyurtma Qiymati',
                'good_direction' => 'higher',
                'default_frequency' => 'daily',
                'default_unit' => 'UZS',
                'is_universal' => false,
                'applicable_industries' => ['ecommerce'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'icon' => '💰',
                'is_active' => true,
            ],
            [
                'category' => 'sales',
                'kpi_code' => 'revenue_per_visitor',
                'kpi_name' => 'Revenue Per Visitor',
                'kpi_name_uz' => 'Tashrif Buyuruvchi Uchun Daromad',
                'measurement_method' => 'Revenue / Visitors',
                'good_direction' => 'higher',
                'default_frequency' => 'daily',
                'default_unit' => 'UZS',
                'is_universal' => false,
                'applicable_industries' => ['ecommerce'],
                'priority_level' => 'high',
                'default_weight' => 2.0,
                'icon' => '📈',
                'is_active' => true,
            ],
            [
                'category' => 'retention',
                'kpi_code' => 'repeat_purchase_rate_ecom',
                'kpi_name' => 'Repeat Purchase Rate (90 days)',
                'kpi_name_uz' => 'Qayta Xarid (90 kun)',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['ecommerce'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'min_business_age' => 'growing',
                'icon' => '🔁',
                'is_active' => true,
            ],
            [
                'category' => 'operational',
                'kpi_code' => 'product_return_rate_ecom',
                'kpi_name' => 'Product Return Rate',
                'kpi_name_uz' => 'Mahsulot Qaytarish',
                'good_direction' => 'lower',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['ecommerce'],
                'priority_level' => 'medium',
                'default_weight' => 1.5,
                'icon' => '↩️',
                'is_active' => true,
            ],
            [
                'category' => 'operational',
                'kpi_code' => 'checkout_completion_rate',
                'kpi_name' => 'Checkout Completion Rate',
                'kpi_name_uz' => 'Checkout Tugatish',
                'measurement_method' => '(Completed / Started) × 100',
                'good_direction' => 'higher',
                'default_frequency' => 'daily',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['ecommerce'],
                'priority_level' => 'high',
                'default_weight' => 2.5,
                'icon' => '✅',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'email_subscriber_growth',
                'kpi_name' => 'Email Subscriber Growth',
                'kpi_name_uz' => 'Email Obunachi O\'sishi',
                'good_direction' => 'higher',
                'default_frequency' => 'monthly',
                'default_unit' => '%',
                'is_universal' => false,
                'applicable_industries' => ['ecommerce'],
                'priority_level' => 'medium',
                'default_weight' => 1.5,
                'icon' => '📧',
                'is_active' => true,
            ],
            [
                'category' => 'marketing',
                'kpi_code' => 'product_page_view_count',
                'kpi_name' => 'Product Page View Count',
                'kpi_name_uz' => 'Mahsulot Sahifa Ko\'rish',
                'good_direction' => 'higher',
                'default_frequency' => 'daily',
                'default_unit' => 'dona',
                'is_universal' => false,
                'applicable_industries' => ['ecommerce'],
                'priority_level' => 'medium',
                'default_weight' => 1.0,
                'icon' => '👀',
                'is_active' => true,
            ],
        ];

        foreach ($kpis as $kpi) {
            KpiTemplate::create($kpi);
        }

        $this->command->info('✓ E-Commerce KPIs seeded (12)');
    }
}
