<?php

namespace Database\Seeders;

use App\Models\LeadSource;
use Illuminate\Database\Seeder;

class LeadSourceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sources = [
            // Digital sources
            [
                'code' => 'instagram_dm',
                'name' => 'Instagram DM',
                'category' => 'digital',
                'icon' => 'instagram',
                'color' => '#E4405F',
                'is_paid' => false,
                'default_cost' => 10000,
                'is_trackable' => true,
                'sort_order' => 1,
            ],
            [
                'code' => 'instagram_ads',
                'name' => 'Instagram Ads',
                'category' => 'digital',
                'icon' => 'instagram',
                'color' => '#E4405F',
                'is_paid' => true,
                'default_cost' => 15000,
                'is_trackable' => true,
                'sort_order' => 2,
            ],
            [
                'code' => 'facebook_messenger',
                'name' => 'Facebook Messenger',
                'category' => 'digital',
                'icon' => 'facebook',
                'color' => '#1877F2',
                'is_paid' => false,
                'default_cost' => 10000,
                'is_trackable' => true,
                'sort_order' => 3,
            ],
            [
                'code' => 'facebook_ads',
                'name' => 'Facebook Ads',
                'category' => 'digital',
                'icon' => 'facebook',
                'color' => '#1877F2',
                'is_paid' => true,
                'default_cost' => 15000,
                'is_trackable' => true,
                'sort_order' => 4,
            ],
            [
                'code' => 'telegram',
                'name' => 'Telegram',
                'category' => 'digital',
                'icon' => 'telegram',
                'color' => '#0088CC',
                'is_paid' => false,
                'default_cost' => 8000,
                'is_trackable' => true,
                'sort_order' => 5,
            ],
            [
                'code' => 'whatsapp',
                'name' => 'WhatsApp',
                'category' => 'digital',
                'icon' => 'whatsapp',
                'color' => '#25D366',
                'is_paid' => false,
                'default_cost' => 0,
                'is_trackable' => true,
                'sort_order' => 6,
            ],
            [
                'code' => 'website_form',
                'name' => 'Website Forma',
                'category' => 'digital',
                'icon' => 'globe',
                'color' => '#4F46E5',
                'is_paid' => false,
                'default_cost' => 12000,
                'is_trackable' => true,
                'sort_order' => 7,
            ],
            [
                'code' => 'google_ads',
                'name' => 'Google Ads',
                'category' => 'digital',
                'icon' => 'google',
                'color' => '#4285F4',
                'is_paid' => true,
                'default_cost' => 25000,
                'is_trackable' => true,
                'sort_order' => 8,
            ],
            [
                'code' => 'yandex_direct',
                'name' => 'Yandex Direct',
                'category' => 'digital',
                'icon' => 'yandex',
                'color' => '#FF0000',
                'is_paid' => true,
                'default_cost' => 20000,
                'is_trackable' => true,
                'sort_order' => 9,
            ],
            [
                'code' => 'email',
                'name' => 'Email',
                'category' => 'digital',
                'icon' => 'mail',
                'color' => '#6B7280',
                'is_paid' => true,
                'default_cost' => 5000,
                'is_trackable' => false,
                'sort_order' => 10,
            ],
            [
                'code' => 'sms',
                'name' => 'SMS',
                'category' => 'digital',
                'icon' => 'message-square',
                'color' => '#10B981',
                'is_paid' => true,
                'default_cost' => 3000,
                'is_trackable' => false,
                'sort_order' => 11,
            ],

            // Offline sources
            [
                'code' => 'flyer',
                'name' => 'Flayer/Broshyura',
                'category' => 'offline',
                'icon' => 'file-text',
                'color' => '#F59E0B',
                'is_paid' => true,
                'default_cost' => 5000,
                'is_trackable' => false,
                'sort_order' => 20,
            ],
            [
                'code' => 'billboard',
                'name' => 'Billboard/Banner',
                'category' => 'offline',
                'icon' => 'image',
                'color' => '#8B5CF6',
                'is_paid' => true,
                'default_cost' => 30000,
                'is_trackable' => false,
                'sort_order' => 21,
            ],
            [
                'code' => 'radio',
                'name' => 'Radio',
                'category' => 'offline',
                'icon' => 'radio',
                'color' => '#EC4899',
                'is_paid' => true,
                'default_cost' => 20000,
                'is_trackable' => false,
                'sort_order' => 22,
            ],
            [
                'code' => 'tv',
                'name' => 'TV',
                'category' => 'offline',
                'icon' => 'tv',
                'color' => '#3B82F6',
                'is_paid' => true,
                'default_cost' => 50000,
                'is_trackable' => false,
                'sort_order' => 23,
            ],
            [
                'code' => 'newspaper',
                'name' => 'Gazeta/Jurnal',
                'category' => 'offline',
                'icon' => 'newspaper',
                'color' => '#6B7280',
                'is_paid' => true,
                'default_cost' => 15000,
                'is_trackable' => false,
                'sort_order' => 24,
            ],
            [
                'code' => 'walk_in',
                'name' => "Do'konga keldi",
                'category' => 'offline',
                'icon' => 'store',
                'color' => '#10B981',
                'is_paid' => false,
                'default_cost' => 0,
                'is_trackable' => false,
                'sort_order' => 25,
            ],
            [
                'code' => 'phone_call',
                'name' => "Telefon qo'ng'iroq",
                'category' => 'offline',
                'icon' => 'phone',
                'color' => '#14B8A6',
                'is_paid' => false,
                'default_cost' => 0,
                'is_trackable' => false,
                'sort_order' => 26,
            ],
            [
                'code' => 'expo_event',
                'name' => 'Expo/Tadbir',
                'category' => 'offline',
                'icon' => 'calendar',
                'color' => '#F97316',
                'is_paid' => true,
                'default_cost' => 100000,
                'is_trackable' => false,
                'sort_order' => 27,
            ],

            // Referral sources
            [
                'code' => 'customer_referral',
                'name' => 'Mijoz tavsiyasi',
                'category' => 'referral',
                'icon' => 'users',
                'color' => '#22C55E',
                'is_paid' => false,
                'default_cost' => 0,
                'is_trackable' => false,
                'sort_order' => 30,
            ],
            [
                'code' => 'partner_referral',
                'name' => 'Hamkor tavsiyasi',
                'category' => 'referral',
                'icon' => 'handshake',
                'color' => '#0EA5E9',
                'is_paid' => true,
                'default_cost' => 50000,
                'is_trackable' => false,
                'sort_order' => 31,
            ],
            [
                'code' => 'employee_referral',
                'name' => 'Xodim tavsiyasi',
                'category' => 'referral',
                'icon' => 'user-check',
                'color' => '#A855F7',
                'is_paid' => true,
                'default_cost' => 30000,
                'is_trackable' => false,
                'sort_order' => 32,
            ],

            // Organic sources
            [
                'code' => 'organic_search',
                'name' => 'Organik qidiruv',
                'category' => 'organic',
                'icon' => 'search',
                'color' => '#059669',
                'is_paid' => false,
                'default_cost' => 0,
                'is_trackable' => true,
                'sort_order' => 40,
            ],
            [
                'code' => 'organic_social',
                'name' => 'Ijtimoiy tarmoq organik',
                'category' => 'organic',
                'icon' => 'share-2',
                'color' => '#7C3AED',
                'is_paid' => false,
                'default_cost' => 0,
                'is_trackable' => false,
                'sort_order' => 41,
            ],
            [
                'code' => 'word_of_mouth',
                'name' => "Og'zaki reklama",
                'category' => 'organic',
                'icon' => 'message-circle',
                'color' => '#64748B',
                'is_paid' => false,
                'default_cost' => 0,
                'is_trackable' => false,
                'sort_order' => 42,
            ],
        ];

        foreach ($sources as $source) {
            LeadSource::updateOrCreate(
                ['code' => $source['code']],
                array_merge($source, ['is_active' => true])
            );
        }
    }
}
