<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('business_kpi_configurations', function (Blueprint $table) {
            $table->id();

            // Business Reference (UUID)
            $table->uuid('business_id');
            $table->foreign('business_id')->references('id')->on('businesses')->onDelete('cascade');

            // Business Classification (Cached for performance)
            $table->string('industry_code', 100)->index();
            $table->string('sub_category', 100)->nullable()->index();
            $table->enum('business_size', ['small', 'medium', 'large']);
            $table->enum('business_maturity', ['new', 'growing', 'established']);

            // Business Goals & Strategy
            $table->enum('primary_goal', [
                'customer_acquisition',
                'revenue_growth',
                'customer_retention',
                'brand_awareness',
                'operational_efficiency',
                'market_expansion',
            ])->default('customer_acquisition');

            $table->json('secondary_goals')->nullable()
                ->comment('Array of additional goals');

            // Selected KPIs
            $table->json('selected_kpis')->comment('Array of KPI codes selected for this business')
                ->comment('["booking_inquiry_volume", "instagram_engagement_rate", ...]');

            // KPI Priorities (Custom per business)
            $table->json('kpi_priorities')->nullable()
                ->comment('{"booking_inquiry_volume": "critical", "story_views": "high"}');

            // KPI Custom Weights (Override defaults)
            $table->json('kpi_weights')->nullable()
                ->comment('{"booking_inquiry_volume": 3.0, "instagram_engagement": 2.0}');

            // Generation Metadata
            $table->boolean('is_auto_generated')->default(true)
                ->comment('Was this configuration auto-generated by the system');
            $table->boolean('customized_by_user')->default(false)
                ->comment('Has the user modified the auto-generated config');
            $table->json('generation_params')->nullable()
                ->comment('Parameters used for auto-generation for audit trail');

            // Configuration Status
            $table->enum('status', ['draft', 'active', 'paused', 'archived'])->default('active')->index();
            $table->timestamp('activated_at')->nullable();
            $table->timestamp('last_reviewed_at')->nullable()
                ->comment('When user last reviewed/confirmed the configuration');

            // Performance Tracking
            $table->integer('total_kpis_count')->default(0);
            $table->integer('critical_kpis_count')->default(0);
            $table->decimal('overall_achievement_rate', 5, 2)->nullable()
                ->comment('Current overall KPI achievement %');

            // Notification Preferences
            $table->json('notification_settings')->nullable()->comment('{
                "daily_digest": true,
                "weekly_summary": true,
                "critical_alerts": true,
                "digest_time": "07:00",
                "channels": ["email", "telegram"]
            }');

            // Review & Optimization
            $table->text('user_notes')->nullable()->comment('User notes about their KPI strategy');
            $table->timestamp('next_review_due')->nullable()
                ->comment('When this configuration should be reviewed next');
            $table->integer('review_frequency_days')->default(90)
                ->comment('How often to prompt user to review KPIs');

            // Audit Trail (UUID for user IDs)
            $table->uuid('created_by_user_id')->nullable();
            $table->foreign('created_by_user_id')->references('id')->on('users')->onDelete('set null');
            $table->uuid('last_modified_by_user_id')->nullable();
            $table->foreign('last_modified_by_user_id')->references('id')->on('users')->onDelete('set null');
            $table->timestamps();
            $table->softDeletes();

            // Indexes
            $table->unique('business_id');
            $table->index(['status', 'activated_at']);
            $table->index(['industry_code', 'sub_category']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('business_kpi_configurations');
    }
};
