<?php

return [
    'ecommerce' => [
        'label' => 'E-commerce do\'kon',
        'label_uz' => 'Onlayn do\'kon',
        'label_ru' => 'Интернет-магазин',
        'description' => 'Mahsulotlar sotish: kiyim, texnika, oziq-ovqat va boshqalar',
        'icon' => 'ShoppingCartIcon',
        'catalog_model' => \App\Models\Store\StoreProduct::class,
        'catalog_table' => 'store_products',
        'catalog_label' => 'Mahsulotlar',
        'catalog_label_singular' => 'Mahsulot',
        'service_class' => \App\Services\Store\Catalog\ProductCatalogService::class,
        'features' => ['cart', 'variants', 'reviews', 'wishlist', 'delivery', 'promo_codes'],
        'catalog_fields' => ['name', 'description', 'price', 'compare_price', 'sku', 'stock_quantity', 'track_stock', 'is_featured'],
        'search_fields' => ['name', 'description', 'sku'],
        'filter_fields' => ['category_id', 'is_active', 'is_featured', 'price_range'],
        'sort_fields' => ['name', 'price', 'created_at', 'sort_order'],
        'has_images' => true,
        'has_variants' => true,
        'has_stock' => true,
    ],

    'service' => [
        'label' => 'Xizmatlar',
        'label_uz' => 'Xizmatlar',
        'label_ru' => 'Услуги',
        'description' => 'Go\'zallik saloni, shifokor, yurist, ta\'mirchi va boshqa xizmatlar',
        'icon' => 'WrenchScrewdriverIcon',
        'catalog_model' => \App\Models\Store\StoreService::class,
        'catalog_table' => 'store_services',
        'catalog_label' => 'Xizmatlar',
        'catalog_label_singular' => 'Xizmat',
        'service_class' => \App\Services\Store\Catalog\ServiceCatalogService::class,
        'features' => ['booking', 'staff', 'schedule', 'reviews', 'wishlist', 'promo_codes'],
        'catalog_fields' => ['name', 'description', 'price', 'duration_minutes', 'requires_staff'],
        'search_fields' => ['name', 'description'],
        'filter_fields' => ['category_id', 'staff_id', 'price_range', 'duration_range'],
        'sort_fields' => ['name', 'price', 'duration_minutes', 'sort_order'],
        'has_images' => false,
        'has_variants' => false,
        'has_stock' => false,
    ],

    'delivery' => [
        'label' => 'Yetkazib berish',
        'label_uz' => 'Yetkazib berish',
        'label_ru' => 'Доставка еды',
        'description' => 'Restoran, kafe, fast-food — taom yetkazib berish',
        'icon' => 'TruckIcon',
        'catalog_model' => \App\Models\Store\StoreMenuItem::class,
        'catalog_table' => 'store_menu_items',
        'catalog_label' => 'Menyu',
        'catalog_label_singular' => 'Taom',
        'service_class' => \App\Services\Store\Catalog\MenuItemCatalogService::class,
        'features' => ['cart', 'modifiers', 'delivery', 'reviews', 'promo_codes'],
        'catalog_fields' => ['name', 'description', 'price', 'preparation_time_minutes', 'calories'],
        'search_fields' => ['name', 'description'],
        'filter_fields' => ['category_id', 'price_range', 'dietary_tags'],
        'sort_fields' => ['name', 'price', 'sort_order'],
        'has_images' => false,
        'has_variants' => false,
        'has_stock' => false,
    ],

    'course' => [
        'label' => 'Kurslar',
        'label_uz' => 'Onlayn kurslar',
        'label_ru' => 'Онлайн-курсы',
        'description' => 'Ta\'lim kurslari, darslar, sertifikatlar',
        'icon' => 'AcademicCapIcon',
        'catalog_model' => \App\Models\Store\StoreCourse::class,
        'catalog_table' => 'store_courses',
        'catalog_label' => 'Kurslar',
        'catalog_label_singular' => 'Kurs',
        'service_class' => \App\Services\Store\Catalog\CourseCatalogService::class,
        'features' => ['cart', 'reviews', 'wishlist', 'promo_codes'],
        'catalog_fields' => ['name', 'description', 'price', 'duration_hours', 'level', 'instructor', 'max_students', 'start_date'],
        'search_fields' => ['name', 'description', 'instructor'],
        'filter_fields' => ['category_id', 'level', 'price_range', 'format'],
        'sort_fields' => ['name', 'price', 'start_date', 'sort_order'],
        'has_images' => false,
        'has_variants' => false,
        'has_stock' => false,
    ],

    'fitness' => [
        'label' => 'Fitnes',
        'label_uz' => 'Fitnes klub',
        'label_ru' => 'Фитнес-клуб',
        'description' => 'Sport zali, yoga, fitnes — obuna va mashg\'ulotlar',
        'icon' => 'HeartIcon',
        'catalog_model' => \App\Models\Store\StoreMembership::class,
        'catalog_table' => 'store_memberships',
        'catalog_label' => 'A\'zoliklar',
        'catalog_label_singular' => 'A\'zolik',
        'service_class' => \App\Services\Store\Catalog\FitnessCatalogService::class,
        'features' => ['cart', 'booking', 'staff', 'schedule', 'reviews', 'promo_codes'],
        'catalog_fields' => ['name', 'description', 'price', 'duration_days', 'features'],
        'search_fields' => ['name', 'description'],
        'filter_fields' => ['price_range', 'duration_range'],
        'sort_fields' => ['name', 'price', 'duration_days', 'sort_order'],
        'has_images' => false,
        'has_variants' => false,
        'has_stock' => false,
    ],

    'realestate' => [
        'label' => 'Ko\'chmas mulk',
        'label_uz' => 'Ko\'chmas mulk',
        'label_ru' => 'Недвижимость',
        'description' => 'Kvartira, uy, ofis — sotish va ijaraga berish',
        'icon' => 'HomeModernIcon',
        'catalog_model' => \App\Models\Store\StoreProperty::class,
        'catalog_table' => 'store_properties',
        'catalog_label' => 'Mulklar',
        'catalog_label_singular' => 'Mulk',
        'service_class' => \App\Services\Store\Catalog\PropertyCatalogService::class,
        'features' => ['wishlist', 'reviews', 'map'],
        'catalog_fields' => ['name', 'description', 'price', 'price_type', 'area_sqm', 'rooms', 'floor', 'address'],
        'search_fields' => ['name', 'description', 'address', 'district'],
        'filter_fields' => ['category_id', 'price_type', 'price_range', 'rooms', 'area_range'],
        'sort_fields' => ['name', 'price', 'area_sqm', 'created_at'],
        'has_images' => true,
        'has_variants' => false,
        'has_stock' => false,
    ],

    'auto' => [
        'label' => 'Avto bozor',
        'label_uz' => 'Avto bozor',
        'label_ru' => 'Авторынок',
        'description' => 'Avtomobillar sotish va sotib olish',
        'icon' => 'TruckIcon',
        'catalog_model' => \App\Models\Store\StoreVehicle::class,
        'catalog_table' => 'store_vehicles',
        'catalog_label' => 'Avtomobillar',
        'catalog_label_singular' => 'Avtomobil',
        'service_class' => \App\Services\Store\Catalog\VehicleCatalogService::class,
        'features' => ['wishlist', 'reviews', 'calculator'],
        'catalog_fields' => ['name', 'description', 'price', 'year', 'mileage_km', 'fuel_type', 'transmission', 'engine_volume'],
        'search_fields' => ['name', 'description', 'make', 'model'],
        'filter_fields' => ['category_id', 'price_range', 'year_range', 'fuel_type', 'transmission', 'body_type'],
        'sort_fields' => ['name', 'price', 'year', 'mileage_km', 'created_at'],
        'has_images' => true,
        'has_variants' => false,
        'has_stock' => false,
    ],

    'event' => [
        'label' => 'Tadbirlar',
        'label_uz' => 'Tadbirlar',
        'label_ru' => 'Мероприятия',
        'description' => 'Konferensiya, konsert, seminar — chipta sotish',
        'icon' => 'CalendarDaysIcon',
        'catalog_model' => \App\Models\Store\StoreEvent::class,
        'catalog_table' => 'store_events',
        'catalog_label' => 'Tadbirlar',
        'catalog_label_singular' => 'Tadbir',
        'service_class' => \App\Services\Store\Catalog\EventCatalogService::class,
        'features' => ['cart', 'tickets', 'reviews', 'wishlist', 'map', 'qr_code'],
        'catalog_fields' => ['name', 'description', 'venue', 'address', 'start_date', 'end_date'],
        'search_fields' => ['name', 'description', 'venue'],
        'filter_fields' => ['category_id', 'date_range', 'price_range'],
        'sort_fields' => ['name', 'start_date', 'created_at'],
        'has_images' => false,
        'has_variants' => false,
        'has_stock' => false,
    ],

    'travel' => [
        'label' => 'Sayohat',
        'label_uz' => 'Sayohat turlari',
        'label_ru' => 'Туры',
        'description' => 'Turlar, sayohat paketlari, ekskursiyalar',
        'icon' => 'GlobeAltIcon',
        'catalog_model' => \App\Models\Store\StoreTour::class,
        'catalog_table' => 'store_tours',
        'catalog_label' => 'Turlar',
        'catalog_label_singular' => 'Tur',
        'service_class' => \App\Services\Store\Catalog\TourCatalogService::class,
        'features' => ['cart', 'booking', 'reviews', 'wishlist', 'promo_codes'],
        'catalog_fields' => ['name', 'description', 'price', 'duration_days', 'max_group_size', 'departure_city'],
        'search_fields' => ['name', 'description', 'departure_city'],
        'filter_fields' => ['category_id', 'price_range', 'duration_range', 'difficulty_level'],
        'sort_fields' => ['name', 'price', 'duration_days', 'created_at'],
        'has_images' => false,
        'has_variants' => false,
        'has_stock' => false,
    ],

    'ondemand' => [
        'label' => 'Talab bo\'yicha',
        'label_uz' => 'Talab bo\'yicha xizmat',
        'label_ru' => 'По запросу',
        'description' => 'Taksi, kuryer, tozalash — talab bo\'yicha xizmatlar',
        'icon' => 'BoltIcon',
        'catalog_model' => \App\Models\Store\StoreServiceRequest::class,
        'catalog_table' => 'store_service_requests',
        'catalog_label' => 'Xizmat turlari',
        'catalog_label_singular' => 'Xizmat turi',
        'service_class' => \App\Services\Store\Catalog\OnDemandCatalogService::class,
        'features' => ['booking', 'staff', 'reviews', 'map'],
        'catalog_fields' => ['name', 'description', 'min_price', 'max_price', 'estimated_duration'],
        'search_fields' => ['name', 'description'],
        'filter_fields' => ['category_id', 'price_range'],
        'sort_fields' => ['name', 'min_price', 'sort_order'],
        'has_images' => false,
        'has_variants' => false,
        'has_stock' => false,
    ],

    'subscription' => [
        'label' => 'Obuna',
        'label_uz' => 'Obuna platformasi',
        'label_ru' => 'Подписка',
        'description' => 'Kontent, video, maqola — oylik obuna',
        'icon' => 'CreditCardIcon',
        'catalog_model' => \App\Models\Store\StoreContentPlan::class,
        'catalog_table' => 'store_content_plans',
        'catalog_label' => 'Obuna rejalari',
        'catalog_label_singular' => 'Obuna rejasi',
        'service_class' => \App\Services\Store\Catalog\SubscriptionCatalogService::class,
        'features' => ['cart', 'reviews', 'promo_codes'],
        'catalog_fields' => ['name', 'description', 'price', 'billing_cycle', 'trial_days', 'features'],
        'search_fields' => ['name', 'description'],
        'filter_fields' => ['billing_cycle', 'price_range'],
        'sort_fields' => ['name', 'price', 'sort_order'],
        'has_images' => false,
        'has_variants' => false,
        'has_stock' => false,
    ],

    'custom' => [
        'label' => 'Moslashuvchan',
        'label_uz' => 'Moslashuvchan katalog',
        'label_ru' => 'Настраиваемый',
        'description' => 'O\'zingiz xohlagan turdagi katalog — erkin maydonlar',
        'icon' => 'PuzzlePieceIcon',
        'catalog_model' => \App\Models\Store\StoreCustomItem::class,
        'catalog_table' => 'store_custom_items',
        'catalog_label' => 'Elementlar',
        'catalog_label_singular' => 'Element',
        'service_class' => \App\Services\Store\Catalog\CustomCatalogService::class,
        'features' => ['cart', 'reviews', 'wishlist', 'promo_codes'],
        'catalog_fields' => ['name', 'description', 'price', 'custom_fields'],
        'search_fields' => ['name', 'description'],
        'filter_fields' => ['category_id', 'price_range'],
        'sort_fields' => ['name', 'price', 'created_at', 'sort_order'],
        'has_images' => false,
        'has_variants' => false,
        'has_stock' => false,
    ],
];
