<?php

namespace App\Http\Controllers;

use App\Models\Business;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Inertia\Inertia;

class WelcomeController extends Controller
{
    /**
     * Show the welcome/instruction page for new users
     */
    public function index()
    {
        $user = Auth::user();

        // If user already has a business, redirect to dashboard
        if ($user->businesses()->exists()) {
            return redirect()->route('business.dashboard');
        }

        return Inertia::render('Welcome');
    }

    /**
     * Show the create business form (for first-time users)
     */
    public function createBusiness()
    {
        $user = Auth::user();

        // If user already has a business, redirect to new-business route
        if ($user->businesses()->exists()) {
            return redirect()->route('new-business');
        }

        return Inertia::render('Welcome/CreateBusiness');
    }

    /**
     * Show the create business form (for users who already have businesses)
     */
    public function newBusiness()
    {
        return Inertia::render('Welcome/CreateBusiness', [
            'isAdditionalBusiness' => true,
        ]);
    }

    /**
     * Store a new business (first time)
     */
    public function storeBusiness(Request $request)
    {
        return $this->createAndStoreBusiness($request);
    }

    /**
     * Store a new business (additional)
     */
    public function storeNewBusiness(Request $request)
    {
        return $this->createAndStoreBusiness($request);
    }

    /**
     * Show the welcome/start page after business creation
     */
    public function start()
    {
        $user = Auth::user();
        $business = $user->businesses()->latest()->first();

        // If no business exists, redirect to create business
        if (!$business) {
            return redirect()->route('welcome.create-business');
        }

        return Inertia::render('Welcome/Start', [
            'business' => $business,
        ]);
    }

    /**
     * Common method to create and store a business
     */
    private function createAndStoreBusiness(Request $request)
    {
        $validated = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'category' => ['required', 'string', 'max:100'],
            'description' => ['nullable', 'string', 'max:1000'],
            'website' => ['nullable', 'url', 'max:255'],
            'region' => ['required', 'string', 'max:100'],
            'employee_count' => ['nullable', 'string', 'max:50'],
            'monthly_revenue' => ['nullable', 'string', 'max:50'],
            'target_audience' => ['nullable', 'string', 'max:500'],
            'main_goals' => ['required', 'array', 'min:1'],
        ], [
            'category.required' => 'Biznes kategoriyasini tanlang',
            'region.required' => 'Viloyatni tanlang',
            'main_goals.required' => 'Kamida bitta maqsad tanlang',
            'main_goals.min' => 'Kamida bitta maqsad tanlang',
        ]);

        // Generate unique slug from business name
        $slug = Str::slug($validated['name']);
        $originalSlug = $slug;
        $counter = 1;
        while (Business::where('slug', $slug)->exists()) {
            $slug = $originalSlug . '-' . $counter;
            $counter++;
        }

        // Create the business (UUID is auto-generated by HasUuid trait)
        $business = Business::create([
            'user_id' => Auth::id(),
            'name' => $validated['name'],
            'slug' => $slug,
            'category' => $validated['category'],
            'description' => $validated['description'] ?? null,
            'website' => $validated['website'] ?? null,
            'city' => $validated['region'],
            'region' => $validated['region'],
            'country' => "O'zbekiston",
            'employee_count' => $validated['employee_count'] ?? null,
            'monthly_revenue' => $validated['monthly_revenue'] ?? null,
            'target_audience' => $validated['target_audience'] ?? null,
            'main_goals' => $validated['main_goals'],
            'onboarding_status' => 'in_progress',
            'onboarding_current_step' => 'basic_info',
        ]);

        // Attach the current user as owner
        $business->users()->attach(Auth::id(), [
            'role' => 'owner',
            'joined_at' => now(),
        ]);

        // Assign owner role using Spatie Permission (if not already)
        if (!Auth::user()->hasRole('owner')) {
            Auth::user()->assignRole('owner');
        }

        // Set the new business as current
        session(['current_business_id' => $business->id]);

        // Redirect to welcome/start page for new businesses
        return redirect()->route('welcome.start')
            ->with('success', 'Biznes muvaffaqiyatli yaratildi!');
    }

    /**
     * Switch to a different business
     */
    public function switchBusiness(Business $business)
    {
        $user = Auth::user();

        // Check if user has access to this business
        if (!$user->businesses()->where('businesses.id', $business->id)->exists()) {
            abort(403, 'Bu biznesga kirish huquqingiz yo\'q');
        }

        // Set the business as current
        session(['current_business_id' => $business->id]);

        // Check if business needs onboarding
        if ($business->onboarding_status !== 'completed') {
            return redirect()->route('onboarding.index')
                ->with('info', "{$business->name} biznesiga o'tdingiz.");
        }

        return redirect()->route('business.dashboard')
            ->with('success', "{$business->name} biznesiga o'tdingiz.");
    }
}
