<?php

namespace App\Http\Controllers;

use App\Models\Business;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Inertia\Inertia;

class WelcomeController extends Controller
{
    /**
     * Show the welcome/instruction page for new users
     */
    public function index()
    {
        $user = Auth::user();

        // If user already has a business, redirect to dashboard
        if ($user->businesses()->exists()) {
            return redirect()->route('business.dashboard');
        }

        return Inertia::render('Welcome');
    }

    /**
     * Show the create business form
     */
    public function createBusiness()
    {
        $user = Auth::user();

        // If user already has a business, redirect to dashboard
        if ($user->businesses()->exists()) {
            return redirect()->route('business.dashboard');
        }

        return Inertia::render('Welcome/CreateBusiness');
    }

    /**
     * Store a new business
     */
    public function storeBusiness(Request $request)
    {
        $validated = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'category' => ['required', 'string', 'max:100'],
            'description' => ['nullable', 'string', 'max:1000'],
            'website' => ['nullable', 'url', 'max:255'],
            'region' => ['required', 'string', 'max:100'],
            'employee_count' => ['nullable', 'string', 'max:50'],
            'monthly_revenue' => ['nullable', 'string', 'max:50'],
            'target_audience' => ['nullable', 'string', 'max:500'],
            'main_goals' => ['required', 'array', 'min:1'],
        ], [
            'category.required' => 'Biznes kategoriyasini tanlang',
            'region.required' => 'Viloyatni tanlang',
            'main_goals.required' => 'Kamida bitta maqsad tanlang',
            'main_goals.min' => 'Kamida bitta maqsad tanlang',
        ]);

        // Generate unique slug from business name
        $slug = Str::slug($validated['name']);
        $originalSlug = $slug;
        $counter = 1;
        while (Business::where('slug', $slug)->exists()) {
            $slug = $originalSlug . '-' . $counter;
            $counter++;
        }

        // Create the business (UUID is auto-generated by HasUuid trait)
        $business = Business::create([
            'user_id' => Auth::id(),
            'name' => $validated['name'],
            'slug' => $slug,
            'category' => $validated['category'],
            'description' => $validated['description'] ?? null,
            'website' => $validated['website'] ?? null,
            'city' => $validated['region'],
            'region' => $validated['region'],
            'country' => "O'zbekiston",
            'employee_count' => $validated['employee_count'] ?? null,
            'monthly_revenue' => $validated['monthly_revenue'] ?? null,
            'target_audience' => $validated['target_audience'] ?? null,
            'main_goals' => $validated['main_goals'],
            'onboarding_status' => 'in_progress',
            'onboarding_current_step' => 'basic_info',
        ]);

        // Attach the current user as owner
        $business->users()->attach(Auth::id(), [
            'role' => 'owner',
            'joined_at' => now(),
        ]);

        // Assign owner role using Spatie Permission
        Auth::user()->assignRole('owner');

        // Redirect to onboarding
        return redirect()->route('onboarding.index')
            ->with('success', 'Biznes muvaffaqiyatli yaratildi! Endi onboarding jarayonini boshlang.');
    }
}
